---
- block:
    - name: Generate Calico YAML
      template:
        src: calico.yaml.j2
        dest: /tmp/calico.yaml

    - name: Apply Calico Configuration
      shell: kubectl apply -f /tmp/calico.yaml

  when: kubernetes_cni == 'cailco'